// generated by stringer -type=packObjectType; DO NOT EDIT

package gitgo

import "fmt"

const _packObjectType_name = "OBJ_COMMITOBJ_TREEOBJ_BLOBOBJ_TAGOBJ_OFS_DELTAOBJ_REF_DELTA"

var _packObjectType_index = [...]uint8{0, 10, 18, 26, 33, 46, 59}

func (i packObjectType) String() string {
	i -= 1
	if i+1 >= packObjectType(len(_packObjectType_index)) {
		return fmt.Sprintf("packObjectType(%d)", i+1)
	}
	return _packObjectType_name[_packObjectType_index[i]:_packObjectType_index[i+1]]
}
