// generated by stringer -type=packObjectType; DO NOT EDIT

package gitgo

import "fmt"

const (
	_packObjectType_name_0 = "OBJ_COMMITOBJ_TREEOBJ_BLOBOBJ_TAG"
	_packObjectType_name_1 = "OBJ_OFS_DELTAOBJ_REF_DELTA"
)

var (
	_packObjectType_index_0 = [...]uint8{0, 10, 18, 26, 33}
	_packObjectType_index_1 = [...]uint8{0, 13, 26}
)

func (i packObjectType) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _packObjectType_name_0[_packObjectType_index_0[i]:_packObjectType_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _packObjectType_name_1[_packObjectType_index_1[i]:_packObjectType_index_1[i+1]]
	default:
		return fmt.Sprintf("packObjectType(%d)", i)
	}
}
